#page title
page_title                                : Emoji Keyboard   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://chrome.google.com/webstore/detail/emoji-keyboard/nekacekgelnakbmhepjioandkacfablo?hl=en&authuser=0   # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/emoji-keyboard.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Emoji Keyboard                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Use emojis anywhere on the web!😊

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Justice Ogbonna                                
your_link                                 : https://www.justiceo.com/                     
your_city                                 : San Francisco, California                                
email_address                             : dev@justiceo.com
facebook_username                         : justice.ogb                                          
instagram_username                        : justice.ogbonna
twitter_username                          : justice_mode
github_username                           : justiceo
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Multilingual Emojis
    description                           : Communicate in any language with a wide selection of emojis.
    fontawesome_icon_name                 : language
    
  - title                                 : Quick Search
    description                           : Find the perfect emoji instantly with a rapid search feature.
    fontawesome_icon_name                 : search

  - title                                 : Integrated Trigger
    description                           : Conveniently access the emoji keyboard with a built-in trigger key.
    fontawesome_icon_name                 : keyboard

  - title                                 : Personalized Shortcuts
    description                           : Set custom shortcut keys for your favorite emojis.
    fontawesome_icon_name                 : hashtag

  - title                                 : Endless Emoji Packs
    description                           : Enjoy unlimited emoji packs for endless expression.
    fontawesome_icon_name                 : infinity
  
  - title                                 : Diverse Skin Tones
    description                           : Represent yourself accurately with multiple skin tone options.
    fontawesome_icon_name                 : hand-spock-o

  - title                                 : Custom Emojis
    description                           : Add your own unique touch by using custom emojis.
    fontawesome_icon_name                 : smile-o 

  - title                                 : Always Up-to-Date
    description                           : Stay current with the latest emoji releases and updates.
    fontawesome_icon_name                 : pencil-square-o 

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
